### ISSUE TITLE
500 error on template generation

### ISSUE THREAD

**Issue by iparr** [nystudio107/vanillaforums#1]
I'm running a reasonably fresh copy of Craft (v2.4.2702) on a standard _Homestead_ box.

When I generate the template as instructed using `{{ vanillaforumsSSO() }}`, a blank page with a 500 error is displayed.

Everything else seems to be working okay. Do you have any pointers?

**Comment by iparr** [comment]
Edit - I worked out from picking through the code that _jsConnectPHP_ was required to be placed somewhere. I'd be happy to update the README to explain this if you think it would help others. This is a helpful plugin.

**Comment by khalwat** [comment]
Oops, sorry about that.  It excluded the commit because jsConnectPHP was a git repo itself.  I've included it in the latest commit, sorry about that.

**Comment by iparr** [comment]
As an exercise, I'm trying to get it so everything can be pulled into the right place using Composer, as soon as I get past this problem: https://github.com/composer/installers/issues/268

Thank you for your help (and your plug-in).
