### ISSUE TITLE
SSO fails when two users have same full name

### ISSUE THREAD

**Issue by tommymarshall** [nystudio107/vanillaforums#2]
This plugin currently uses the Full Name of users when attempting to create an account and log them in. This is problematic for large a large user base as two people with the same name will conflict and show an unclear "Create Account" screen, even though they should already have an account.

Instead, assigning the craft username would get around this problem.

**Comment by khalwat** [comment]
Agreed.  I'll make the changes and push to the repo in a bit.

**Comment by khalwat** [comment]
Okay, the change has been committed.

**Comment by khalwat** [comment]
I remember why I didn't do it this way actually... it was because I have it set to use email addresses as their user name.  And for semi-obvious reasons, I didn't want people's email addresses displayed publicly.

So what we do now is this:

```
        if (craft()->config->get('useEmailAsUsername'))
            $data['name'] = $currentUser->getFullName();
        else
            $data['name'] = $currentUser->username;
```
