### ISSUE TITLE
"The client_id parameter is missing" Error

### ISSUE THREAD

**Issue by jeremiahrich** [nystudio107/vanillaforums#4]
I followed the install instructions, but when I try to make the template using the following code:
{{ vanillaforumsSSO() }}

It returns the following error:
{"error":"invalid_request","message":"The client_id parameter is missing."}

However, when I use this code:
var vanilla_sso = '{{ vanillaforumsSSOEmbed() }}';

It works correctly and returns the proper response. Tried re-entering the Client ID and Secret just in case to no avail. Any help would be greatly appreciated. Thank you, and thank you for the awesome plugin!

**Comment by khalwat** [comment]
Sorry, somehow I missed this. Have you solved the problem?

**Comment by migmake** [comment]
Hi  Khalwat.
I filled the two values in the plugin.
But I got same problem after following the process step by step.
{"error":"invalid_request","message":"The client_id parameter is missing."}

**Comment by khalwat** [comment]
It's working on my test install. Is something else somehow not set up properly?
